apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
spec:
  selector:
    matchLabels:
      app: result-app
  replicas: 3
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
      - name: result-app-container
        image: shubhanjanweb/result-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80