apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
spec:
  selector:
    matchLabels:
      app: voting-app
  replicas: 3
  template:
    metadata:
      labels:
        app: voting-app
    spec:
      containers:
      - name: voting-app-container
        image: shubhanjanweb/voting-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80