apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
spec:
  selector:
    matchLabels:
      app: worker-app
  replicas: 3
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app-container
        image: shubhanjanweb/worker-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80