apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: result-app-replicaset
  labels:
    name: result-app-replicaset
    app: demo-voting-app
spec:
  selector:
    matchLabels: 
      name: result-app-pod
  replicas: 3
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: result-app-container
          image: shubhanjanweb/result-app:latest
          ports:
            - containerPort: 80
