apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: deom-voting-app
spec:
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voting-app
  replicas: 3
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: demo-voting-app
    spec:
      containers:
       - name: worker-app
         image: venuopalshastri/worker-app:latest
        


