apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis-deployment
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      type: back-end
  replicas: 3
  template:
    metadata:
      name: redis-pod
      labels:
        app: redis
        type: back-end
    spec:
      containers:
      - name: redis-container
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 6379
