apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-replicaset
  labels:
    name: redis-replicaset
    app: demo-voting-app
spec:
  selector:
    matchLabels: 
      name: redis-pod
  replicas: 3
  template:
    metadata:
      name: redis-pod
    labels:
      name: redis-pod
      app: demo-voting-demo
    spec:
      containers:
      - name: redis-container
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 6379
