apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: postgres-replicaset
  labels:
    name: postgres-replicaset
    app: demo-voting-app
spec:
  selector:
    matchLabels: 
      name: postgres-pod
  replicas: 3
  template:
    metadata:
      name: postgres-pod
    labels:
      name: postgres-pod
      app: demo-voting-demo
    spec:
      containers:
      - name: postgres-container
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust