apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: worker-app-replicaset
  labels:
    name: worker-app-replicaset
    app: demo-voting-app
spec:
  selector:
    matchLabels: 
      name: worker-app-pod
  replicas: 3
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: worker-app-demo
    spec:
      containers:
      - name: worker-app-container
        image: shubhanjanweb/worker-app:latest
        ports:
        - containerPort: 80
