apiVersion: v1
kind: Service
metadata:
  name: msone-service
spec: 
  type: NodePort
  ports:
    - targetPort: 3000
      port: 80
      nodePort: 30008
  selector:
    name: msone-pod
    app: microservice-one-demo