apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: voting-app-replicaset
  labels:
    name: voting-app-replicaset
    app: demo-voting-app
spec:
  selector:
    matchLabels: 
      name: voting-app-pod
  replicas: 3
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app-container
          image: shubhanjanweb/voting-app:latest
          ports:
            - containerPort: 80
