apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
spec:
  type: NodePort
  selector:
    name: voting-app-pod
    app: voting-app-demo
  ports:
  - targetPort: 80
    port: 80
    nodePort: 30008
