apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      type: back-end
  replicas: 3
  template:
    metadata:
      name: worker-app-pod
      labels:
        app: worker-app
        type: back-end
    spec:
      containers:
      - name: worker-app-container
        image: shubhanjanweb/worker-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
